export const FETCH_MOVIES = "FETCH_MOVIES";
export const SET_POPULAR_MOVIES = "SET_POPULAR_MOVIES";
export const SET_SEARCHED_MOVIES = "SET_SEARCHED_MOVIES";
export const CLEAR_MOVIES = "CLEAR_MOVIES";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
